platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

target 'WiaTagKit_Example' do
  pod 'WiaTagKit', :path => '../'

  target 'WiaTagKit_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
